Txpool 4844 upgrades Part 2
ledgerwatch/erigon-lib pull request #1125
Opened 2023-09-13 12:15 UTC by somnathb1

Fix some peer-review comments from the last related PR, and add some enhancements

#### Change summary
- Addition of a flag for BlobSlots - for max allowed blobs per account in txpool
- Use BlobFee from the block to validate txs in the pool
- Let go of unwound blob txn's onNewBlock, if not present in the cache; we don't request them again from the network

Related: https://github.com/ledgerwatch/erigon/pull/8213 https://github.com/ledgerwatch/interfaces/pull/195

2023-09-17 01:18 UTC, AskAlexSharov requested changes

2023-09-17 01:18 UTC, AskAlexSharov commented on txpool/pool.go
> +		changed = blobFee != p.pendingBlobFee.Load()
“Read then write” on atomic - it’s race-condition. Please use  CompareAndSwap operation.

2023-09-17 01:18 UTC, AskAlexSharov commented on txpool/pool.go
> +	if mt.Tx.Type == types.BlobTxType && mt.Tx.BlobFeeCap.Cmp(uint256.NewInt(p.pendingBlobFee.Load())) < 0 {
uint256 has method Less

2023-09-17 01:18 UTC, AskAlexSharov commented on txpool/pool.go
> +	for worst := pending.Worst(); pending.Len() > 0 && (worst.subPool < BaseFeePoolBits || worst.minFeeCap.Cmp(uint256.NewInt(pendingBaseFee)) < 0 || (worst.Tx.Type == types.BlobTxType && worst.Tx.BlobF
Can we avoid “NewInt” inside loop - for optimization. Because we are also inside global mutex of txpool - and better unlock it as fast as possible.

2023-09-18 01:32 UTC, AskAlexSharov commented on txpool/pool.go
> +	for worst := pending.Worst(); pending.Len() > 0 && (worst.subPool < BaseFeePoolBits || worst.minFeeCap.Cmp(uint256.NewInt(pendingBaseFee)) < 0 || (worst.Tx.Type == types.BlobTxType && worst.Tx.BlobF
Is it in “wei”? Can it have uint64 overflow?

2023-09-18 01:37 UTC, AskAlexSharov submitted a review, later dismissed
- i’m not sure that it’s safe to cast any uint256 to uint64, because it can be bigger than uint64
- please take a look at existing fuzzing tests for txpool - are they still work? Need add there new check?

2023-09-18 12:43 UTC, yperbasis commented on go.sum
> +github.com/ledgerwatch/interfaces v0.0.0-20230912104607-5501cfd6e5af h1:gGWTa4p8npycnK9gVBbZxMSOBvUgM80lsDU9rnFqyHU=
It'd be nice to run `go mod tidy`

2023-09-18 13:05 UTC, yperbasis commented on txpool/pool_test.go
> +	//try to replace it with required price bump to all transaction fields - should be successful
It'd be nice to add tests with individual bumps as well. At the moment it's not clear from the test what exactly should be bumped and by how much.

2023-09-19 08:29 UTC, yperbasis requested changes

2023-09-19 08:29 UTC, yperbasis commented on txpool/fetch.go
>  						}
Otherwise (`Type != types2.BlobTxType`) `utx` should be added to `unwindTxs`

2023-09-19 09:13 UTC, yperbasis approved these changes

2023-09-20 11:23 UTC, merged