compress: implemented consensed huffman pattern tables
ledgerwatch/erigon-lib pull request #536
Opened 2022-07-20 13:31 UTC by awskii

Optionally added ability to condense pattern tables to reduce required amount of RAM.
By default condensing is disabled for the sake of faster decompression.
To set condensing of tables larger than 64 elements needed to call  

`compression.SetDecompressionTableCondensity(fromBitSize int)` with `fromBitSize` = 6. Set to 9 to totally disable condensing (since we don't use tables larger than 2^9) 

before calling `NewDecompressor(compressedFilePath)`

2022-07-21 07:51 UTC, AskAlexSharov commented on compress/decompress.go
> +// Condensing reduces memory consumption but co
didn't finish doc line

2022-07-22 10:00 UTC, AskAlexSharov approved these changes

2022-07-23 02:29 UTC, AskAlexSharov requested changes
Got nil-pointer exception when 		`compress.SetDecompressionTableCondensity(6)` and send rpc request on Goerli: `{  "jsonrpc": "2.0", "method": "eth_getBlockByNumber",  "params": [    "0x4C4B40",true  ],  "id": 537758}`

Stack:
```
RPC method eth_getBlockByNumber crashed: runtime error: invalid memory address or nil pointer dereference
[service.go:217 panic.go:838 panic.go:220 signal_unix.go:818 decompress.go:429 decompress.go:517 block_reader.go:501 block_reader.go:423 block_snapshots.go:200 block_snapshots.go:613 block_reader.go:422 eth_api.go:163 eth_api.go:143 eth_api.go:221 eth_block.go:199 value.go:556 value.go:339 service.go:222 handler.go:507 handler.go:412 handler.go:360 handler.go:191 handler.go:284 asm_amd64.s:1571]
```

2022-08-02 12:15 UTC, awskii commented
Did `compress.SetDecompressionTableCondensity(6)` been set before call of `NewDecompression`? Strictly required to be so due to tables creation during NewDecompression watches current value of condensity AND during search over the table which could lead to such awkward panic. Will investigate later.

2022-08-02 14:11 UTC, AskAlexSharov commented
Yes, error happen only when set.

do you say - need set it when create .seg file? It changing .seg file?

2022-08-03 14:07 UTC, awskii commented
No it doesnt affect seg files at all. I meant that condensity should be set before NewDecompressor eg

```
compress.SetDecompressionTableCondensity(6)
d, err := compress.NewDecompressor(fname)
...
```

2022-08-04 01:34 UTC, AskAlexSharov commented
Yep, i did

2022-08-18 16:38 UTC, awskii commented
Rebased this branch on erigon-lib/main and with erigon/82fb73a545ab101f3f54755b10cbcf207c6b339e (current devel) set condensity to 6 and with it started erigon:

```
{
  "jsonrpc": "2.0",
  "id": 537758,
  "result": {
    "difficulty": "0x2",
    "extraData": "0x726f6e696e2d6b61697a656e0000000000000000000000000000000000000000c62d46426b3fe1864f5a7b6a09d3d51960e5f1c8c23e6cbe64ddb9d42061c35b11525a63f92f4047211d7d8e0e1ad6cbe04aff52b55f2e5d13b4f0e6251f03c801",
    "gasLimit": "0xb745f0",
    "gasUsed": "0xb73cd1",
    "hash": "0x0c795e5bb06f493cdf2b95f5b0280ed0f5109b595977feaf13dfa406df4279ac",
    "logsBloom": "0x7601801144282072ae1ca110010860040440080205050200108f0080320100a5421206412822e054028997661040942928810182025c0a8000024148a08569609681574084401bc814c05d080102d02803c00804100485400a1100581291b4800250ba551629f0328210001808a008a281004b07005e6100004020380a00408c004246002e60044400004088044e609f0022518160d09d818502468012060000680800942a9a4440a65944290c901983028500050c82760cca08a51ca03c042000068a32120020200282002320091511aac00086020058582100014ab3886805092a0bc801282296a411020c181b14b1e8e0030001880f046480188604a51444",
    "miner": "0x0000000000000000000000000000000000000000",
    "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "nonce": "0x0000000000000000",
    "number": "0x4c4b40",
    "parentHash": "0x3a8a09de2b009bb811fbc1ab4721048e92642c8930f740e38100cb5cd66eec6b",
    "receiptsRoot": "0x3eb0dc7a748e850812404394a56d49a3b86caabd49b8133b298802609850a805",
    "sha3Uncles": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
    "size": "0x7701",
    "stateRoot": "0xe12f0adeb0b20d4dd9daca2a6d71245e9acc0c2a3b07e000204231eaa60f581e",
    "timestamp": "0x60cec6a2",
    "totalDifficulty": "0x6f9ead",
    "transactions": [
      {
        "blockHash": "0x0c795e5bb06f493cdf2b95f5b0280ed0f5109b595977feaf13dfa406df4279ac",
        "blockNumber": "0x4c4b40",
        "from": "0x5a5a554811739cc6026ea56011ce1cf4c80a1346",
        "gas": "0x5208",
        "gasPrice": "0xe8d4a51000",
        "hash": "0x523f2b9d30dfcd8f778541247f988fe56faf3d37850557bf72cd8577b705bc9e",
        "input": "0x",
        "nonce": "0x2a",
        "to": "0xf6adb604c75c9c8f11b45969b2af6d252d1467a7",
        "transactionIndex": "0x0",
        "value": "0x58d15e176280000",
        "type": "0x0",
        "chainId": "0x5",
        "v": "0x2e",
        "r": "0xd48fa2210afd3c3dce3ebd15237f4f45132ddcb21a59e90c24954daa7c3b4a4a",
        "s": "0x59c5a62c2e79973655a1359c944e516ffa8de8ce6f96d8fd689dd45176246be5"
      },
      {
        "blockHash": "0x0c795e5bb06f493cdf2b95f5b0280ed0f5109b595977feaf13dfa406df4279ac",
        "blockNumber": "0x4c4b40",
        "from": "0xed504e39ee3c6179a6575e1607ed7e3250dcd212",
        "gas": "0x7cacf",
        "gasPrice": "0xe8d4a51000",
        "hash": "0xafadfa5fb3fdedbfd40d2a4b37cf853f3e76bf8e6ce01acf96db678f27959a87",
        "input": "0x0e5c011e000000000000000000000000e8afc9988ac87c430570907e401c0febb53507cb",
        "nonce": "0x2",
        "to": "0xe6f4e3af0d5d9bbc77d2e4b69c5f589d0fc7b182",
        "transactionIndex": "0x1",
        "value": "0x0",
        "type": "0x0",
        "chainId": "0x5",
        "v": "0x2d",
        "r": "0x7058e3b4dc0d893b199ee65016c28bb3b29a1379546564a8e69b71f5dd4f3f6e",
        "s": "0x363c19d93ac294c1eebcc22195a33e12984dcdbab81aa3e529c2375c1993d932"
      },
      {
        "blockHash": "0x0c795e5bb06f493cdf2b95f5b0280ed0f5109b595977feaf13dfa406df4279ac",
        "blockNumber": "0x4c4b40",
        "from": "0x0b580c4e2ba84ab4685fe0add25ade48ae292be3",
        "gas": "0xf4fb",
        "gasPrice": "0xe8d4a51000",
        "hash": "0xc9b96b9000875c6b638015d208a187fad54d0f303879848b32277a666ece06c6",
        "input": "0xa9059cbb000000000000000000000000d913b5f3c47fd27d7268bfb543cae39158bfae4c000000000000000000000000000000000000000000000000002386f26fc10000",
        "nonce": "0x1",
        "to": "0x2ac3c1d3e24b45c6c310534bc2dd84b5ed576335",
        "transactionIndex": "0x2",
        "value": "0x0",
        "type": "0x0",
        "chainId": "0x5",
        "v": "0x2d",
        "r": "0x1ac32b6b503618787e52eb4b9c130a6614ef72dde51bea5a0aa0fdf242c583a4",
        "s": "0x53d7737909d8423605c0b634d8765b60328bae9ad0a6d5835dc12a66a2981043"
      },
      {
        "blockHash": "0x0c795e5bb06f493cdf2b95f5b0280ed0f5109b595977feaf13dfa406df4279ac",
        "blockNumber": "0x4c4b40",
        "from": "0x35ad42942d05504c3cc951a6b4123453f06750df",
        "gas": "0x493e0",
        "gasPrice": "0x8bb2c97000",
        "hash": "0x9acbad5b35ecbfdc00ada4315f4bf46346b94e07ede9121edae2648249e26e06",
        "input": "0x0d5f26590000000000000000000000003327ec18c5b2d1349c5dcaf1146d28330b5ec4f40000000000000000000000000000000000000000000000000000001264c4560000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000041ce5628a0613913c0c7938b16d279b637a858ab21002d685e41ce49f507244e8e676bdbaae1ed830bf67a8109de74f3cae427f1c423676b4bc0f92028c3f0cbba1b00000000000000000000000000000000000000000000000000000000000000",
        "nonce": "0x8b",
        "to": "0x5cc506cb191a7e0478a91054d38a9f87e88d56df",
        "transactionIndex": "0x3",
        "value": "0x0",
        "type": "0x0",
        "chainId": "0x5",
        "v": "0x2d",
        "r": "0xe6b86c09181faea1ff47852172341e983e9218140df6d6ae96192419937d793b",
        "s": "0x75d516fc049abc31979564868caf9cfd599e7e850b85781e9ae3a8bedc0d5eda"
      },
      {
        "blockHash": "0x0c795e5bb06f493cdf2b95f5b0280ed0f5109b595977feaf13dfa406df4279ac",
        "blockNumber": "0x4c4b40",
        "from": "0x4612c65b1e6396d0ac083139dfe6ec8f3f2104b6",
        "gas": "0x493e0",
        "gasPrice": "0x8bb2c97000",
        "hash": "0xeda82a87787b05d1ce0725c571aa283e77826b3b41ccda918222925ed9551db1",
        "input": "0x0d5f26590000000000000000000000001c33aa9ca7b0d10333ea547cc30c87dec51875c6000000000000000000000000000000000000000000000000000000147d35700000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000041c4cae0b42c2110b0addc4918c5d4f38319edf33455f253b375c61240cb4ee89b3af19c458eebabb4c0472ec5240d120a754c5eb2a13537653a57ffefa85884df1b00000000000000000000000000000000000000000000000000000000000000",
        "nonce": "0x8d",
        "to": "0x2292ca36e8a76655840ad7ea45d500a137684320",
        "transactionIndex": "0x4",
        "value": "0x0",
        "type": "0x0",
        "chainId": "0x5",
        "v": "0x2e",
        "r": "0xc3fdda18bf25e72b819edef4bc8202a547f8559ed94b9d97c29e42df7a0991ce",
        "s": "0x189704d6d65f774d08ade2cf80a107e6b504815e8c8e3303ebe7e476e8a81855"
      },
      {
        "blockHash": "0x0c795e5bb06f493cdf2b95f5b0280ed0f5109b595977feaf13dfa406df4279ac",
        "blockNumber": "0x4c4b40",
        "from": "0xa16c30f9460c07059b259c71a62e5b229c784a5c",
        "gas": "0x493e0",
        "gasPrice": "0x8bb2c97000",
        "hash": "0xc7b85e5f9103450eb09d50e3499b8dca4235b3c7e651a6a34f63d52d14eebe5b",
        "input": "0x0d5f26590000000000000000000000008bb5727e2d0a81f6fa82e84224d1241ae2dcf5a400000000000000000000000000000000000000000000000000000011b1f3f80000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000041f1aa3c1f8f6ba96c2fbecc54813b6d3059b6cb3613833e6fd45a3940fab970390f56712f34a6e3534957a872bb71ef9746ea1912facc76cada6985318e80da971b00000000000000000000000000000000000000000000000000000000000000",
        "nonce": "0x73",
        "to": "0xe45cb629c8e5871f2ccc4a471e8e13df2a40aa9a",
        "transactionIndex": "0x5",
        "value": "0x0",
        "type": "0x0",
        "chainId": "0x5",
        "v": "0x2e",
        "r": "0xea676872561c2d21a5019a008fa9d1d12c2a1b88c0b000125765c1055b82648e",
        "s": "0x3d6f687780fea78408886480178fd64438753fb7275540d08dcac0f2126779c9"
      },
      {
        "blockHash": "0x0c795e5bb06f493cdf2b95f5b0280ed0f5109b595977feaf13dfa [...]

2022-08-22 02:11 UTC, merged