fixing c-99
ledgerwatch/erigon-lib pull request #579
Opened 2022-08-11 17:10 UTC by enriavil1

Solving this error reported to me: 
`Building erigon
# github.com/ledgerwatch/erigon-lib/sais
utils.c: In function 'lcp_kasai':
utils.c:6:5: error: 'for' loop initial declarations are only allowed in C99 mode
     for (int i = 0, j = 0; i < sa_size; i++)`

2022-08-12 05:25 UTC, AskAlexSharov approved these changes

2022-08-12 08:31 UTC, yperbasis requested changes
But after the change `int i = 0` is still declared inside the `for` loop, is it not?

I suggest not to bother with changing the code and instead recommend C99 mode for compilation.

2022-08-12 09:11 UTC, enriavil1 commented
> But after the change `int i = 0` is still declared inside the `for` loop, is it not?
> 
> I suggest not to bother with changing the code and instead recommend C99 mode for compilation.

Where can I recommend C99 mode?

2022-08-12 09:26 UTC, yperbasis commented
> Where can I recommend C99 mode?

For gcc the [command line option](https://renenyffenegger.ch/notes/development/languages/C-C-plus-plus/GCC/options/std) is `-std=c99`

I'm not sure how we build these C files though. Perhaps @AskAlexSharov can advise.

2022-08-12 13:36 UTC, AskAlexSharov commented
Golang does build it for us. It calling gcc under the hood. See Makefile part about CGO_CFLAGS

2022-08-12 13:37 UTC, AskAlexSharov commented
You can write “ -std=c99” in .go file which is in directory with .c files. Example: https://github.com/torquem-ch/mdbx-go/blob/2fbaf3122d4b216301e0802b765ac95d498c48fc/mdbx/mdbx.go#L134

2022-08-12 17:05 UTC, enriavil1 commented
> You can write “ -std=c99” in .go file which is in directory with .c files. Example: https://github.com/torquem-ch/mdbx-go/blob/2fbaf3122d4b216301e0802b765ac95d498c48fc/mdbx/mdbx.go#L134

I actually don't have access to that torquem repo

2022-08-13 02:34 UTC, AskAlexSharov commented
@enriavil1 granted you access to `mdbx-go` and `log` projects. but `sais` package is in erigon-lib project.

2022-08-13 15:15 UTC, merged