changed baseFeeCap from uint64 -> uint256
ledgerwatch/erigon-lib pull request #646
Opened 2022-09-20 15:20 UTC by enriavil1

Changing FeeCap to use uint256 instead of uint64 for gnosis chain

2022-09-21 15:28 UTC, yperbasis requested changes

2022-09-21 15:28 UTC, yperbasis commented on txpool/pool.go
> +	minFeeCap := *max256
2^256 overflows 256 bit. Use `SetAllOne()` instead (=2^256-1)

2022-09-21 18:52 UTC, enriavil1 commented on txpool/pool.go
> +	minFeeCap := *max256
Done

2022-09-22 09:58 UTC, yperbasis requested changes

2022-09-22 09:58 UTC, yperbasis commented on txpool/pool.go
> +			than.minFeeCap.Sub(&than.minFeeCap, &pendingBaseFee)
Don't change `than.minFeeCap`. Introduce a temporary variable for the difference instead.

2022-09-22 09:58 UTC, yperbasis commented on txpool/pool.go
> +			if mt.minFeeCap.Cmp(uint256.NewInt(mt.minTip)) <= 0 {
You need a temporary variable to calculate the difference `mt.minFeeCap-pendingBaseFee`

2022-09-22 12:03 UTC, yperbasis requested changes

2022-09-22 12:03 UTC, yperbasis commented on txpool/pool.go
> +		difference.Sub(&than.minFeeCap, &pendingBaseFee)
There were 2 differences here previously:
`mt.minFeeCap-pendingBaseFee`
and
`than.minFeeCap-pendingBaseFee`

2022-09-22 15:16 UTC, AskAlexSharov commented
FYI: you can fuzz by `go test -fuzz=FuzzOnNewBlocks ./txpool`

2022-09-22 15:18 UTC, enriavil1 commented
> FYI: you can fuzz by `go test -fuzz=FuzzOnNewBlocks ./txpool`

Wdym fuzz?

2022-09-22 15:36 UTC, yperbasis requested changes
"fuzz" here means fuzz testing: https://en.wikipedia.org/wiki/Fuzzing

And yeah,
```
go test -fuzz=FuzzOnNewBlocks ./txpool
```
fails with
```
rlp parse transaction: feeCap: rlp parse: integer encoding for RLP must not have leading zeros: 00
```

2022-09-23 07:35 UTC, yperbasis approved these changes

2022-09-23 10:47 UTC, merged